# Site settings
title: rizzassz's blog
email: 
description: > # this means to ignore newlines until "baseurl:"
    This is rizzassz's github pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rizzassz
github_username:  

# Build settings
markdown: kramdown
